application: word-count-mr
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: "2.6"